[project]
name = "advent-of-code-2021"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.2",
    "ruff>=0.14.8",
]
